---
- name: Install Terraform Homebrew Packages
  become: false
  community.general.homebrew:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
  loop: "{{ terraform_brew_pkgs }}"

# look up user path and make this generic for linux and osx...
- name: Generate Terraform CLI Config (terraformrc)
  ansible.builtin.template:
    src: terraformrc.j2
    dest: "/Users/{{ terraform_user_id }}/.terraformrc"
    owner: "{{ terraform_user_id }}"
    mode: '0644'
