---
- name: Install Terraform Homebrew Packages
  become: false
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ terraform_brew_pkgs }}"

- name: Install golang
  become: false
  community.general.homebrew:
    name: "go@{{ terraform_golang_version }}"
  when: terraform_golang_version is defined
