---
- name: "Verify TF binary {{ item.value }}"
  stat:
    path: "/usr/local/bin/terraform-{{ item.key }}"
  register: tf_binary

- name: "Verify TF version {{ item.value }}"
  command: "/usr/local/bin/terraform-{{ item.key }} --version"
  failed_when: false
  changed_when: false
  register: tf_version

- name: Download Terraform alt versions
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/terraform/{{ item.value }}/terraform_{{ item.value }}_{{ ansible_system | lower }}_{{ terraform_arch[ansible_architecture] }}.zip"
    dest: /tmp
    owner: "{{ terraform_user_id }}"
  register: tf_downloaded
  when: not tf_binary.stat.exists or item.value not in tf_version.stdout
