---
- include_tasks: osx.yml
  when: ansible_os_family == 'Darwin'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Manage Terraform CLI credentials
  ansible.builtin.template:
    dest: "~{{ terraform_user_id }}/.terraformrc"
    src: terraformrc.j2
    owner: "{{ terraform_user_id }}"
    mode: u=rw
  when: terraform_backend_creds is defined
  # no_log: true

- name: Manage Terraform CLI extra config
  ansible.builtin.blockinfile:
    path: "~{{ terraform_user_id }}/.terraformrc"
    create: true
    owner: "{{ terraform_user_id }}"
    mode: u=rw
    block: "{{ terraform_cli_config_extra }}"
    marker: "# {mark}  --------------------- ANSIBLE MANAGED BLOCK"
  when: terraform_cli_config_extra is defined

- include_tasks: terraform.yml
  with_dict: "{{ terraform_versions }}"
