---
# - include_tasks: Debian.yml
#   when: ansible_os_family == 'Debian'
#   become: true

# - include_tasks: nix.yml
#   when: ansible_os_family != 'Windows'
#   become: true

- include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'

# - include_tasks: Windows.yml
#   when: ansible_os_family == 'Windows'

# - name: Install pip packages
#   pip:
#     name: "{{ terraform_pip_pkgs }}"
#     extra_args: --user