---
- name: Generate Terraform CLI Config (terraformrc)
  ansible.builtin.template:
    src: terraformrc.j2
    dest: "~{{ terraform_user_id }}/.terraformrc"
    owner: "{{ terraform_user_id }}"
    mode: '0644'
  when: terraform_backends is defined