---
- name: Generate Terraform CLI Config (terraformrc)
  ansible.builtin.blockinfile:
    path: "~{{ terraform_user_id }}/.terraformrc"
    owner: "{{ terraform_user_id }}"
    mode: u=rw
    block: |
      credentials "{{ item.key }}" {
        token = "{{ item.value }}"
      }
    marker: "# Ansible managed block - creds for host {{ item.key }}"
  when: terraform_backend_creds is defined
  loop: "{{ terraform_backend_creds | dict2items }}"
  no_log: true

- name: Download Terraform alternate versions
  ansible.builtin.unarchive:
    url: "https://releases.hashicorp.com/terraform/{{ item.value }}/terraform_{{ item.value }}_{{ ansible_system | lower }}_{{ terraform_arch[ansible_architecture] }}.zip"
    dest: "/usr/local/bin/terraform{{ item.key }}"
    owner: "{{ terraform_user_id }}"
    mode: u=rwx,g=rwx,o=rx
    remote_src: true
  loop: "{{ terraform_alt_versions | dict2items }}"