---
- include: nix_downloads.yml tf_version={{ item }}
  with_items: "{{ tf_versions }}"

- name: Create symlink for default Terraform binary version
  ansible.builtin.file:
    src: "/usr/local/bin/terraform-{{ tf_default_version }}"
    dest: "/usr/local/bin/terraform"
    mode: u=rwx,g=rx,o=x
    owner: "{{ tf_user_id }}"
    group: admin
    state: link

# - name: Ensure Terraform plugins directory exists for user on *nix
#   ansible.builtin.file:
#     path: "{{ tf_user_paths[ansible_system]. }}"
#     state: directory
#     mode: "{{ tf_plugin_path[ansible_system].mode }}"
#     owner: "{{ tf_user_id }}"
#     group: admin
