---
- name: Generate Terraform CLI Config (terraformrc)
  ansible.builtin.blockinfile:
    path: "~{{ terraform_user_id }}/.terraformrc"
    owner: "{{ terraform_user_id }}"
    mode: u=rw
    block: |
      credentials "{{ item.key }}" {
        token = "{{ item.value }}"
      }
    marker: "# {mark} ANSIBLE MANAGED BLOCK - creds for host {{ item.key }}"
  when: terraform_backend_creds is defined
  loop: "{{ terraform_backend_creds | dict2items }}"
  no_log: true

- include_tasks: download_alt_versions.yml
  loop: "{{ terraform_alt_versions | dict2items }}"
  when: terraform_alt_versions is defined
