---
- name: Uninstall Terraform Homebrew Packages
  become: false
  community.general.homebrew:
    state: absent
    name: terraform
    install_options: --ignore-dependencies

- name: Install Terraform Homebrew Packages
  become: false
  community.general.homebrew:
    state: present
