---
- name: Uninstall Terraform Homebrew Packages
  become: false
  community.general.homebrew:
    state: absent
    name:
      - terragrunt
      - terraform
  when: terraform_versions['default'] == 'tfenv'

- name: Install Terraform Homebrew Packages
  become: false
  community.general.homebrew:
    state: present
    name: "{{ terraform_brew_packages + ['tfenv'] if terraform_versions.default == 'tfenv' else terraform_brew_packages }}"
