---
- name: Download Terraform binary
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/terraform/
      {{ tf_version }}/terraform_{{ tf_version }}_
      {{ ansible_system | lower }}_{{ system_arch[ansible_architecture] }}.zip"
    dest: /tmp
  when: tf_bin_check.stat.exists == 'false'

- name: "Extract Terraform binary {{ tf_version }}"
  ansible.builtin.unarchive:
    src: "/tmp/terraform_{{ tf_version }}_{{ ansible_system | lower }}_amd64.zip"
    dest: /tmp
    remote_src: true
    creates: "/usr/local/bin/terraform-{{ tf_version }}"
  # when: tf_bin_check.stat.exists == 'false'