---
- name: Install Chocolatey package (Terraform)
  win_chocolatey:
    name: "{{ tf_versions }}"
    state: present
    version: "{{ tf_install_version }}"

- name: Install Chocolatey package (Terraform - tflint)
  win_chocolatey:
    name: "{{ tf_packages }}"
    state: present

- name: Ensure Terraform plugins directory exists for user
  win_file:
    path: "{{ tf_plugin_path[ansible_os_family].path }}"
    state: directory

- name: Set perms on Terraform plugins directory exists for user on Windows
  win_acl_inheritance:
    path: "{{ tf_plugin_path[ansible_os_family].path }}"
    state: present
    reorganize: true
