---
- name: Converge
  hosts: all
  vars:
    user_id: chris
  tasks:

    - name: Add the user needed to test role with defaults
      ansible.builtin.user:
        name: "{{ user_id }}"

    - name: "Include terraform"
      include_role:
        name: "ansible-role-terraform"
      vars:
        terraform_golang_version: 1.16
        terraform_version: 1.1.4
        terraform_alt_versions:
          102: 1.0.2
