---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    tf_outdated: 'is out of date'
  tasks:
  - name: Get Terraform version
    ansible.builtin.command:
      cmd: terraform --version
    register: tf_output
    changed_when: False

  - name: Terraform version is latest
    ansible.builtin.debug:
      msg: "{{ tf_output.stdout_lines }}"
    changed_when: False
    when: tf_outdated in tf_output.stdout
