name: Ansible CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  default:
    uses: Diehlabs/shared-workflows/.github/workflows/ansible-ci.yml@v0.0.3
